### ISSUE TITLE
Mesh Shape not in javascript

### ISSUE THREAD

**Issue by tarzzz** [pydy/pydy-viz#61]
Implement mesh shape in addFrames

**Comment by moorepants** [comment]
If this isn't in the JS side, then what happens when you try to use it from the Python side and run the animation?

**Comment by tarzzz** [comment]
Nothing will happen. It wont be drawn in the animation.

**Comment by moorepants** [comment]
Shouldn't it raise an error? At least raise an NotImplementedError on the python side if someone tries to use it.
