### ISSUE TITLE
Cylinder lengths

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy-viz#67]
The cylinder length is called a height on the JS side. These parameters are not in sync. This should be tested (i.e. all parameter names on the JS and Python side need to be ensured to be the same with tests). Right now it is impossible to set the length of the cylinder in the visualization.

**Comment by tarzzz** [comment]
https://github.com/PythonDynamics/pydy-viz/pull/46

**Comment by moorepants** [comment]
Is this fixed?

**Comment by moorepants** [comment]
I'm not sure this was ever fixed. Was it fixed?

**Comment by tarzzz** [comment]
Yes it was fixed!
