### ISSUE TITLE
Cone vs Cylinder

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy-viz#68]
The Cone class should should allow editing of the tip radius from the Python side.

**Comment by tarzzz** [comment]
Cone tip radius automatically set to base_radius/100. PR https://github.com/PythonDynamics/pydy-viz/pull/46

**Comment by moorepants** [comment]
Unless the PR is short and sweet you should reference the actual commit that fixes the bug, e.g:

Commit 6bee55744 fixes this issue.
