### ISSUE TITLE
Play, pause, and stop buttons don't act as expected

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy-viz#71]
If I press Play once, then I can pause an stop the animation fine.

But if I press play two or more times in succession the animation speeds up with each press of play. This is nice because I have some sort of speed control. But then if I want to pause the animation I have to press pause the same number of times I pressed play, same goes for stop.

Ideally play, pause, and stop would work as expected with one click and subsequent clicks do nothing. We would then have a speed control slider for the frame rate.

**Comment by tarzzz** [comment]
fixed in PR https://github.com/PythonDynamics/pydy-viz/pull/46
