### ISSUE TITLE
Dependency specification in setup.py

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy-viz#79]
We should specify minimum dependencies in the setup.py file. This should work with older versions of numpy.

Is matplotlib a dependency? I forget.

**Comment by moorepants** [comment]
Everything should work with the latest version of anaconda.

**Comment by moorepants** [comment]
@tarzzz What are the current dependencies of pydy-viz? Is it only NumPy and SymPy? Or is matplotlib a dep?

**Comment by moorepants** [comment]
matplotlib is imported here: https://github.com/pydy/pydy-viz/blob/master/pydy_viz/light.py

**Comment by moorepants** [comment]
Ok, deps seem to be:
- SymPy (>=0.7.3)
- NumPy (>=1.6.1)
- matplotlib (>=1.0?)

**Comment by tarzzz** [comment]
Fixed in #79
