### ISSUE TITLE
Lots of text displays to the screen

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy-viz#84]
This behavior may not be good for the the notebook:

![base - mozilla firefox_001](https://f.cloud.github.com/assets/276007/1948660/b984ebc4-80a1-11e3-92bd-11853e96a1ef.png)

The favicon errors shouldn't be there, and I'm not sure it is useful to show the data sent messages.

**Comment by moorepants** [comment]
Also note that when you call "scene.display()" in the notebook nothing happens, no text displays to the screen showing where to point your browser. But if you open the link 'localhost:8000' then the text displays. We need the link to display as soon as `scene.display()` is called.

**Comment by moorepants** [comment]
It may also be nice to have the viz server running in a background process, so it doesn't block Ipython.

**Comment by tarzzz** [comment]
The text was more for debugging purposes, and I left it there, because it was in background, Now It should be removed I guess.

**Comment by moorepants** [comment]
Ok, we should remove it then.

**Comment by tarzzz** [comment]
#101
