### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy-viz#85]
This is what I get in firefox:

![mozilla firefox_002](https://f.cloud.github.com/assets/276007/1948670/b56f4254-80a2-11e3-8aa1-6dce29d99640.png)

Looks like Firefox 4.0+ has partial webgl support: http://caniuse.com/webgl

We are using pretty basic stuff, any idea why it isn't working?

**Comment by moorepants** [comment]
We need to check this in safari and IE too.

The Akron tutorial will be on windows machines and I don't know which browser will be available. I'll check.

**Comment by tarzzz** [comment]
fixed in PR https://github.com/PythonDynamics/pydy-viz/pull/98
