### ISSUE TITLE
Trying to visualize the origin fails

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy-viz#87]
Seems like if you try to visualize a point that lies on the origin of the Scene, you get a dot product error. This should be a simple fix.

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-81-34f508cc7fa3> in <module>()
----> 1 scene.generate_visualization_json(coordinates + speeds, constants, y, numerical_constants)

/home/moorepants/src/pydy-viz/pydy_viz/scene.pyc in generate_visualization_json(self, dynamic_variables, constant_variables, dynamic_values, constant_values, save_to)
    307                                               constant_variables,
    308                                               dynamic_values,
--> 309                                               constant_values)
    310         outfile = open(self.saved_json_file, 'w')
    311         outfile.write(json.dumps(self._data_dict, indent=4,

/home/moorepants/src/pydy-viz/pydy_viz/scene.pyc in generate_visualization_dict(self, dynamic_variables, constant_variables, dynamic_values, constant_values)
    225         for frame in self.visualization_frames:
    226             frame.generate_transformation_matrix( 
--> 227                                     self._reference_frame, self._origin)
    228             frame.generate_numeric_transform_function(
    229                                   dynamic_variables, constant_variables)

/home/moorepants/src/pydy-viz/pydy_viz/visualization_frame.pyc in generate_transformation_matrix(self, reference_frame, point)
    226         _point_vector = self.origin.pos_from(point).express(reference_frame)
    227 
--> 228         self._transform[3, 0] = _point_vector.dot(reference_frame.x)
    229         self._transform[3, 1] = _point_vector.dot(reference_frame.y)
    230         self._transform[3, 2] = _point_vector.dot(reference_frame.z)

AttributeError: 'Zero' object has no attribute 'dot'
```

**Comment by moorepants** [comment]
That is, if the point has a zero velocity in the scene's base reference frame, things fail. We want to visualize the ankle point in the tutorial.

**Comment by chrisdembia** [comment]
Try using a different remote? Bad joke.

**Comment by moorepants** [comment]
yeah, bad enough that I don't get it.

**Comment by chrisdembia** [comment]
Like, git origin.

**Comment by moorepants** [comment]
:)

**Comment by tarzzz** [comment]
why is it forming into a Zero object. It should be a 
<code>sympy.physics.mechanics.essential.Vector</code>
as the output from Vector.express(reference_frame)
can you point me to the notebook(or code-snippet) where this error is. I am unable to replicate it.

**Comment by tarzzz** [comment]
SymPy version difference maybe? 
Vector.express might be working differently in older versions, for expressing point w.r.t. itself, as in:
<code> point.pos_from(point).express(some_reference_frame) </code>
might be Zero(Symbol) in some version, and sympy.physics.mechanics.essential.Vector in other version.

**Comment by moorepants** [comment]
You can try it out here:

https://github.com/PythonDynamics/pydy-tutorial-pycon-2014/blob/master/notebooks/base.ipynb

Uncomment the visualization so that all of the objects are are generated. It was failing on trying to visualize the ankle point which has a velocity of zero in the inertial reference frame.

This notebook works with the latest sympy + master on pydy-code-gen and master on pydy-viz.

**Comment by moorepants** [comment]
There has been work on this in recent commits about vectors and zeros.

This should all work with sympy 0.7.3+ for the tutorial.

**Comment by moorepants** [comment]
Also note that we never visualized the origin point in the conical pendulum example.

**Comment by tarzzz** [comment]
One more thing. Can you please add the dependencies, (in README maybe!). I
am having slight trouble in running the notebooks. It shows some errors,
which I think most probably are due to different versions of packages in my
system.

**Comment by moorepants** [comment]
The dependencies are in pydy-code-gen's readme and in the setup.py file.

**Comment by tarzzz** [comment]
Fixed in sympy master
