### ISSUE TITLE
IPython plugin

### ISSUE THREAD

**Issue by tarzzz** [pydy/pydy-viz#90]
A Plugin which allows smooth display of the animations in the IPython Output cell

**Comment by moorepants** [comment]
IPython 2.0 is coming out soon and it has the new JS interactive widgets feature. I think this is ideal for integrating pydy-viz into an IPython notebook. But this is unlikely to happen before the conference(s).

I don't think this is a priority for the conference, but could be icing on the cake if you actually have time to implement it.
