### ISSUE TITLE
Using a web framework like flask or django for pydy-viz

### ISSUE THREAD

**Issue by pramttl** [pydy/pydy-viz#92]
pydy_viz currently uses a server.py file with a custom defined server code.

The server used in pydy_viz needs a lot of custom functionality. The current implementation provides that functionality but might lack in performance leading to slower speeds in visualizations.
The flask framework offers a server with some advantages. Further the framework has the advantagte of being wsgi compliant and will lead to cleaner code.

I would suggest (flask)[https://github.com/mitsuhiko/flask] over django for this case since it is very light < 600kb and it opens interesting doors to the application.

**Comment by moorepants** [comment]
Using a web framework is way too much overhead for what we are doing. All we do is write out a single bit of HTML that loads our javascript.

The speed of the visualizations has no dependence on a web framework, it only depends on the JavaScript engine and code, the user's GPU, and the user's CPU.

Even the lightest weight web framework, bottle, is too much for what we are doing. In fact, we don't even really need the server we have in the code right now. We don't have a database, we don't pass data from Python to JS with requests, or anything. All we do is generate a json file with some data from python and then load that data into a JS script for rendering.

**Comment by pramttl** [comment]
@moorepants 

Passing data from Python to Javascript is not how it should be done. Ideally, the JS should be fetching the data form a python daemon or server. (and that too asyncrhonously)

The need for a server is important in my opinion, if not immediate.
I have worked on a visualization projects before with similar architectures called [pgmpy_viz](https://github.com/pgmpy/pgmpy_viz), and [ganetiviz](https://github.com/pramttl/ganeti_webmgr/tree/feature/13569/ganeti_web/ganetiviz) where I faced similar design decisions. A light, http compliant server was not essential at first but subsequently important. You don't want to be writing a full Http compliant server from scratch and then working on improving the server and solving server bugs when the main idea is to spend more time on Javascript & WebGL side code improvements.

Other than Flask, Django their are much specific options like [SimpleHTTPServer](http://docs.python.org/2/library/simplehttpserver.html) which are a part of core-python.

Again; I am not sure if these are on the project priority. You are the best judge on that.

**Comment by moorepants** [comment]
FYI, we already use SimpleHTTPServer, but haven't implemented requesting the json data. This is a minor detail. You are welcome to submit PRs for improvements in this area, but we are very unlikely to introduce a dependency on any web framework. It would be akin to using a chainsaw to slice a loaf of bread.

You can also look back on the wiki, in the IRC logs, and pydy/sympy mailing list logs to see the history of these decisions and why it is the way it is. At the moment we aren't trying to develop a web app, we are simply trying to create basic visualizations that can ultimately be shared easily via the web. In fact, our target was and still is IPython. IPython is used by the vast majority of users that would be interested in this software and it is installed with all scientific python distributions. IPython offers a tornado based server and json protocol for passing data to and from python and the browser. If we us anything more complicated, it will be IPython's server architecture. IPython 2.0 is including interactive JS widgets for the notebook, which will make controlling the visualizations via python very easy. These are likely where the priorities will lie for the future. I don't see any use for flask or django at the moment. Now if someone ever wants to make some kind of web app with persistence and data storage based on this work, then maybe those tools are useful, but not as it stands.
